// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/ctrl/ctrl.go
//
// Generated by this command:
//
//	mockgen -source=./internal/ctrl/ctrl.go -destination=mocks/mock_repos.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/JMURv/par-pro/products/pkg/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockAppRepo is a mock of AppRepo interface.
type MockAppRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAppRepoMockRecorder
}

// MockAppRepoMockRecorder is the mock recorder for MockAppRepo.
type MockAppRepoMockRecorder struct {
	mock *MockAppRepo
}

// NewMockAppRepo creates a new mock instance.
func NewMockAppRepo(ctrl *gomock.Controller) *MockAppRepo {
	mock := &MockAppRepo{ctrl: ctrl}
	mock.recorder = &MockAppRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppRepo) EXPECT() *MockAppRepoMockRecorder {
	return m.recorder
}

// AddToFavorites mocks base method.
func (m *MockAppRepo) AddToFavorites(ctx context.Context, uid, itemID uuid.UUID) (*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddToFavorites", ctx, uid, itemID)
	ret0, _ := ret[0].(*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddToFavorites indicates an expected call of AddToFavorites.
func (mr *MockAppRepoMockRecorder) AddToFavorites(ctx, uid, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddToFavorites", reflect.TypeOf((*MockAppRepo)(nil).AddToFavorites), ctx, uid, itemID)
}

// CategoryFiltersSearch mocks base method.
func (m *MockAppRepo) CategoryFiltersSearch(ctx context.Context, query string, page, size int) (*model.PaginatedFilterData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategoryFiltersSearch", ctx, query, page, size)
	ret0, _ := ret[0].(*model.PaginatedFilterData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CategoryFiltersSearch indicates an expected call of CategoryFiltersSearch.
func (mr *MockAppRepoMockRecorder) CategoryFiltersSearch(ctx, query, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategoryFiltersSearch", reflect.TypeOf((*MockAppRepo)(nil).CategoryFiltersSearch), ctx, query, page, size)
}

// CategorySearch mocks base method.
func (m *MockAppRepo) CategorySearch(ctx context.Context, query string, page, size int) (*model.PaginatedCategoryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategorySearch", ctx, query, page, size)
	ret0, _ := ret[0].(*model.PaginatedCategoryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CategorySearch indicates an expected call of CategorySearch.
func (mr *MockAppRepoMockRecorder) CategorySearch(ctx, query, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategorySearch", reflect.TypeOf((*MockAppRepo)(nil).CategorySearch), ctx, query, page, size)
}

// CreateCategory mocks base method.
func (m *MockAppRepo) CreateCategory(ctx context.Context, c *model.Category) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, c)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockAppRepoMockRecorder) CreateCategory(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockAppRepo)(nil).CreateCategory), ctx, c)
}

// CreateItem mocks base method.
func (m *MockAppRepo) CreateItem(ctx context.Context, i *model.Item) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateItem", ctx, i)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateItem indicates an expected call of CreateItem.
func (mr *MockAppRepoMockRecorder) CreateItem(ctx, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateItem", reflect.TypeOf((*MockAppRepo)(nil).CreateItem), ctx, i)
}

// CreatePromotion mocks base method.
func (m *MockAppRepo) CreatePromotion(ctx context.Context, p *model.Promotion) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePromotion", ctx, p)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePromotion indicates an expected call of CreatePromotion.
func (mr *MockAppRepoMockRecorder) CreatePromotion(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePromotion", reflect.TypeOf((*MockAppRepo)(nil).CreatePromotion), ctx, p)
}

// DeleteCategory mocks base method.
func (m *MockAppRepo) DeleteCategory(ctx context.Context, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockAppRepoMockRecorder) DeleteCategory(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockAppRepo)(nil).DeleteCategory), ctx, slug)
}

// DeleteItem mocks base method.
func (m *MockAppRepo) DeleteItem(ctx context.Context, uid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", ctx, uid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockAppRepoMockRecorder) DeleteItem(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockAppRepo)(nil).DeleteItem), ctx, uid)
}

// DeletePromotion mocks base method.
func (m *MockAppRepo) DeletePromotion(ctx context.Context, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePromotion", ctx, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePromotion indicates an expected call of DeletePromotion.
func (mr *MockAppRepoMockRecorder) DeletePromotion(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePromotion", reflect.TypeOf((*MockAppRepo)(nil).DeletePromotion), ctx, slug)
}

// GetCategoryBySlug mocks base method.
func (m *MockAppRepo) GetCategoryBySlug(ctx context.Context, slug string) (*model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryBySlug", ctx, slug)
	ret0, _ := ret[0].(*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryBySlug indicates an expected call of GetCategoryBySlug.
func (mr *MockAppRepoMockRecorder) GetCategoryBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryBySlug", reflect.TypeOf((*MockAppRepo)(nil).GetCategoryBySlug), ctx, slug)
}

// GetFavorites mocks base method.
func (m *MockAppRepo) GetFavorites(ctx context.Context, uid uuid.UUID) ([]*model.Favorite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFavorites", ctx, uid)
	ret0, _ := ret[0].([]*model.Favorite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFavorites indicates an expected call of GetFavorites.
func (mr *MockAppRepoMockRecorder) GetFavorites(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavorites", reflect.TypeOf((*MockAppRepo)(nil).GetFavorites), ctx, uid)
}

// GetItemByUUID mocks base method.
func (m *MockAppRepo) GetItemByUUID(ctx context.Context, uid uuid.UUID) (*model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemByUUID", ctx, uid)
	ret0, _ := ret[0].(*model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemByUUID indicates an expected call of GetItemByUUID.
func (mr *MockAppRepoMockRecorder) GetItemByUUID(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemByUUID", reflect.TypeOf((*MockAppRepo)(nil).GetItemByUUID), ctx, uid)
}

// GetPromotion mocks base method.
func (m *MockAppRepo) GetPromotion(ctx context.Context, slug string) (*model.Promotion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPromotion", ctx, slug)
	ret0, _ := ret[0].(*model.Promotion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPromotion indicates an expected call of GetPromotion.
func (mr *MockAppRepoMockRecorder) GetPromotion(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPromotion", reflect.TypeOf((*MockAppRepo)(nil).GetPromotion), ctx, slug)
}

// ItemAttrSearch mocks base method.
func (m *MockAppRepo) ItemAttrSearch(ctx context.Context, query string, size, page int) (*model.PaginatedItemAttrData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ItemAttrSearch", ctx, query, size, page)
	ret0, _ := ret[0].(*model.PaginatedItemAttrData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ItemAttrSearch indicates an expected call of ItemAttrSearch.
func (mr *MockAppRepoMockRecorder) ItemAttrSearch(ctx, query, size, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemAttrSearch", reflect.TypeOf((*MockAppRepo)(nil).ItemAttrSearch), ctx, query, size, page)
}

// ItemSearch mocks base method.
func (m *MockAppRepo) ItemSearch(ctx context.Context, query string, size, page int) (*model.PaginatedItemsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ItemSearch", ctx, query, size, page)
	ret0, _ := ret[0].(*model.PaginatedItemsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ItemSearch indicates an expected call of ItemSearch.
func (mr *MockAppRepoMockRecorder) ItemSearch(ctx, query, size, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ItemSearch", reflect.TypeOf((*MockAppRepo)(nil).ItemSearch), ctx, query, size, page)
}

// ListCategories mocks base method.
func (m *MockAppRepo) ListCategories(ctx context.Context, page, size int) (*model.PaginatedCategoryData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories", ctx, page, size)
	ret0, _ := ret[0].(*model.PaginatedCategoryData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockAppRepoMockRecorder) ListCategories(ctx, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockAppRepo)(nil).ListCategories), ctx, page, size)
}

// ListCategoryFilters mocks base method.
func (m *MockAppRepo) ListCategoryFilters(ctx context.Context, slug string) ([]*model.Filter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoryFilters", ctx, slug)
	ret0, _ := ret[0].([]*model.Filter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategoryFilters indicates an expected call of ListCategoryFilters.
func (mr *MockAppRepoMockRecorder) ListCategoryFilters(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategoryFilters", reflect.TypeOf((*MockAppRepo)(nil).ListCategoryFilters), ctx, slug)
}

// ListCategoryItems mocks base method.
func (m *MockAppRepo) ListCategoryItems(ctx context.Context, slug string, page, size int, filters map[string]any, sort string) (*model.PaginatedItemsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategoryItems", ctx, slug, page, size, filters, sort)
	ret0, _ := ret[0].(*model.PaginatedItemsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCategoryItems indicates an expected call of ListCategoryItems.
func (mr *MockAppRepoMockRecorder) ListCategoryItems(ctx, slug, page, size, filters, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategoryItems", reflect.TypeOf((*MockAppRepo)(nil).ListCategoryItems), ctx, slug, page, size, filters, sort)
}

// ListItems mocks base method.
func (m *MockAppRepo) ListItems(ctx context.Context, page, size int) (*model.PaginatedItemsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItems", ctx, page, size)
	ret0, _ := ret[0].(*model.PaginatedItemsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItems indicates an expected call of ListItems.
func (mr *MockAppRepoMockRecorder) ListItems(ctx, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItems", reflect.TypeOf((*MockAppRepo)(nil).ListItems), ctx, page, size)
}

// ListItemsByLabel mocks base method.
func (m *MockAppRepo) ListItemsByLabel(ctx context.Context, label string, page, size int) (*model.PaginatedItemsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemsByLabel", ctx, label, page, size)
	ret0, _ := ret[0].(*model.PaginatedItemsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemsByLabel indicates an expected call of ListItemsByLabel.
func (mr *MockAppRepoMockRecorder) ListItemsByLabel(ctx, label, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemsByLabel", reflect.TypeOf((*MockAppRepo)(nil).ListItemsByLabel), ctx, label, page, size)
}

// ListPromotionItems mocks base method.
func (m *MockAppRepo) ListPromotionItems(ctx context.Context, slug string, page, size int) (*model.PaginatedPromoItemsData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPromotionItems", ctx, slug, page, size)
	ret0, _ := ret[0].(*model.PaginatedPromoItemsData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPromotionItems indicates an expected call of ListPromotionItems.
func (mr *MockAppRepoMockRecorder) ListPromotionItems(ctx, slug, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPromotionItems", reflect.TypeOf((*MockAppRepo)(nil).ListPromotionItems), ctx, slug, page, size)
}

// ListPromotions mocks base method.
func (m *MockAppRepo) ListPromotions(ctx context.Context, page, size int) (*model.PaginatedPromosData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPromotions", ctx, page, size)
	ret0, _ := ret[0].(*model.PaginatedPromosData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPromotions indicates an expected call of ListPromotions.
func (mr *MockAppRepoMockRecorder) ListPromotions(ctx, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPromotions", reflect.TypeOf((*MockAppRepo)(nil).ListPromotions), ctx, page, size)
}

// ListRelatedItems mocks base method.
func (m *MockAppRepo) ListRelatedItems(ctx context.Context, uid uuid.UUID) ([]*model.RelatedProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRelatedItems", ctx, uid)
	ret0, _ := ret[0].([]*model.RelatedProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRelatedItems indicates an expected call of ListRelatedItems.
func (mr *MockAppRepoMockRecorder) ListRelatedItems(ctx, uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRelatedItems", reflect.TypeOf((*MockAppRepo)(nil).ListRelatedItems), ctx, uid)
}

// PromotionSearch mocks base method.
func (m *MockAppRepo) PromotionSearch(ctx context.Context, query string, page, size int) (*model.PaginatedPromosData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromotionSearch", ctx, query, page, size)
	ret0, _ := ret[0].(*model.PaginatedPromosData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PromotionSearch indicates an expected call of PromotionSearch.
func (mr *MockAppRepoMockRecorder) PromotionSearch(ctx, query, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromotionSearch", reflect.TypeOf((*MockAppRepo)(nil).PromotionSearch), ctx, query, page, size)
}

// RemoveFromFavorites mocks base method.
func (m *MockAppRepo) RemoveFromFavorites(ctx context.Context, uid, itemID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFromFavorites", ctx, uid, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFromFavorites indicates an expected call of RemoveFromFavorites.
func (mr *MockAppRepoMockRecorder) RemoveFromFavorites(ctx, uid, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFromFavorites", reflect.TypeOf((*MockAppRepo)(nil).RemoveFromFavorites), ctx, uid, itemID)
}

// UpdateCategory mocks base method.
func (m *MockAppRepo) UpdateCategory(ctx context.Context, slug string, c *model.Category) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, slug, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockAppRepoMockRecorder) UpdateCategory(ctx, slug, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockAppRepo)(nil).UpdateCategory), ctx, slug, c)
}

// UpdateItem mocks base method.
func (m *MockAppRepo) UpdateItem(ctx context.Context, uid uuid.UUID, i *model.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", ctx, uid, i)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockAppRepoMockRecorder) UpdateItem(ctx, uid, i any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockAppRepo)(nil).UpdateItem), ctx, uid, i)
}

// UpdatePromotion mocks base method.
func (m *MockAppRepo) UpdatePromotion(ctx context.Context, slug string, p *model.Promotion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePromotion", ctx, slug, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePromotion indicates an expected call of UpdatePromotion.
func (mr *MockAppRepoMockRecorder) UpdatePromotion(ctx, slug, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePromotion", reflect.TypeOf((*MockAppRepo)(nil).UpdatePromotion), ctx, slug, p)
}

// MockDiscovery is a mock of Discovery interface.
type MockDiscovery struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryMockRecorder
}

// MockDiscoveryMockRecorder is the mock recorder for MockDiscovery.
type MockDiscoveryMockRecorder struct {
	mock *MockDiscovery
}

// NewMockDiscovery creates a new mock instance.
func NewMockDiscovery(ctrl *gomock.Controller) *MockDiscovery {
	mock := &MockDiscovery{ctrl: ctrl}
	mock.recorder = &MockDiscoveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscovery) EXPECT() *MockDiscoveryMockRecorder {
	return m.recorder
}

// Deregister mocks base method.
func (m *MockDiscovery) Deregister() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deregister")
	ret0, _ := ret[0].(error)
	return ret0
}

// Deregister indicates an expected call of Deregister.
func (mr *MockDiscoveryMockRecorder) Deregister() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deregister", reflect.TypeOf((*MockDiscovery)(nil).Deregister))
}

// FindServiceByName mocks base method.
func (m *MockDiscovery) FindServiceByName(ctx context.Context, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindServiceByName", ctx, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindServiceByName indicates an expected call of FindServiceByName.
func (mr *MockDiscoveryMockRecorder) FindServiceByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindServiceByName", reflect.TypeOf((*MockDiscovery)(nil).FindServiceByName), ctx, name)
}

// Register mocks base method.
func (m *MockDiscovery) Register() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register")
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockDiscoveryMockRecorder) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockDiscovery)(nil).Register))
}

// MockCacheService is a mock of CacheService interface.
type MockCacheService struct {
	ctrl     *gomock.Controller
	recorder *MockCacheServiceMockRecorder
}

// MockCacheServiceMockRecorder is the mock recorder for MockCacheService.
type MockCacheServiceMockRecorder struct {
	mock *MockCacheService
}

// NewMockCacheService creates a new mock instance.
func NewMockCacheService(ctrl *gomock.Controller) *MockCacheService {
	mock := &MockCacheService{ctrl: ctrl}
	mock.recorder = &MockCacheServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheService) EXPECT() *MockCacheServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCacheService) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCacheServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCacheService)(nil).Close))
}

// Delete mocks base method.
func (m *MockCacheService) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheServiceMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheService)(nil).Delete), ctx, key)
}

// GetCode mocks base method.
func (m *MockCacheService) GetCode(ctx context.Context, key string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCode", ctx, key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCode indicates an expected call of GetCode.
func (mr *MockCacheServiceMockRecorder) GetCode(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCode", reflect.TypeOf((*MockCacheService)(nil).GetCode), ctx, key)
}

// GetToStruct mocks base method.
func (m *MockCacheService) GetToStruct(ctx context.Context, key string, dest any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToStruct", ctx, key, dest)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetToStruct indicates an expected call of GetToStruct.
func (mr *MockCacheServiceMockRecorder) GetToStruct(ctx, key, dest any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToStruct", reflect.TypeOf((*MockCacheService)(nil).GetToStruct), ctx, key, dest)
}

// InvalidateKeysByPattern mocks base method.
func (m *MockCacheService) InvalidateKeysByPattern(ctx context.Context, pattern string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateKeysByPattern", ctx, pattern)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateKeysByPattern indicates an expected call of InvalidateKeysByPattern.
func (mr *MockCacheServiceMockRecorder) InvalidateKeysByPattern(ctx, pattern any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateKeysByPattern", reflect.TypeOf((*MockCacheService)(nil).InvalidateKeysByPattern), ctx, pattern)
}

// Set mocks base method.
func (m *MockCacheService) Set(ctx context.Context, t time.Duration, key string, val any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, t, key, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheServiceMockRecorder) Set(ctx, t, key, val any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheService)(nil).Set), ctx, t, key, val)
}
