// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/ctrl/sso/sso.go
//
// Generated by this command:
//
//	mockgen -source=./internal/ctrl/sso/sso.go -destination=mocks/mock_sso.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSSOSvc is a mock of SSOSvc interface.
type MockSSOSvc struct {
	ctrl     *gomock.Controller
	recorder *MockSSOSvcMockRecorder
}

// MockSSOSvcMockRecorder is the mock recorder for MockSSOSvc.
type MockSSOSvcMockRecorder struct {
	mock *MockSSOSvc
}

// NewMockSSOSvc creates a new mock instance.
func NewMockSSOSvc(ctrl *gomock.Controller) *MockSSOSvc {
	mock := &MockSSOSvc{ctrl: ctrl}
	mock.recorder = &MockSSOSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSOSvc) EXPECT() *MockSSOSvcMockRecorder {
	return m.recorder
}

// GetIDByToken mocks base method.
func (m *MockSSOSvc) GetIDByToken(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDByToken", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDByToken indicates an expected call of GetIDByToken.
func (mr *MockSSOSvcMockRecorder) GetIDByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDByToken", reflect.TypeOf((*MockSSOSvc)(nil).GetIDByToken), ctx, token)
}

// ValidateToken mocks base method.
func (m *MockSSOSvc) ValidateToken(ctx context.Context, token string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockSSOSvcMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockSSOSvc)(nil).ValidateToken), ctx, token)
}
