// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/discovery/discovery.go
//
// Generated by this command:
//
//	mockgen -source=./internal/discovery/discovery.go -destination=mocks/mock_discovery.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
